### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by dweindl**
* re-format
* add RTD link
* fix some typos

### CODE REVIEW

**Review by dilpath — APPROVED** [review]
Nice, thanks! Was the formatting automatic or manual?

**Comment by dweindl** [comment]
> Nice, thanks! Was the formatting automatic or manual?

Mostly auto :sweat_smile:

**Comment by dilpath** [comment]
> > Nice, thanks! Was the formatting automatic or manual?
> 
> Mostly auto 😅

Ah, some tool like `black` or your IDE? I can try to integrate it into CI or pre-commit.

**Comment by dweindl** [comment]
> > > Nice, thanks! Was the formatting automatic or manual?
> > 
> > 
> > Mostly auto 😅
> 
> Ah, some tool like `black` or your IDE? I can try to integrate it into CI or pre-commit.

IDE. Required some intervention. For non-code, I'd only do that in a supervised manner.

**Pull request merged**
